//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rhome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rhome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication5.Rhome", typeof(Rhome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LAbout {
            get {
                return ResourceManager.GetString("LAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Ladress {
            get {
                return ResourceManager.GetString("Ladress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A life without the daily traffic jams.
        /// </summary>
        public static string LAlifewithout {
            get {
                return ResourceManager.GetString("LAlifewithout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Development.
        /// </summary>
        public static string LAppDeveloper {
            get {
                return ResourceManager.GetString("LAppDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baku State University.
        /// </summary>
        public static string LBakuState {
            get {
                return ResourceManager.GetString("LBakuState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string LBlog {
            get {
                return ResourceManager.GetString("LBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Reviews.
        /// </summary>
        public static string LClient {
            get {
                return ResourceManager.GetString("LClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute wonderful ! I am completely                                     blown away.The very best.I was amazed       at the quality.
        /// </summary>
        public static string LClientDescript {
            get {
                return ResourceManager.GetString("LClientDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string LCommunication {
            get {
                return ResourceManager.GetString("LCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compar Academy.
        /// </summary>
        public static string LComparAcademy {
            get {
                return ResourceManager.GetString("LComparAcademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string LContact {
            get {
                return ResourceManager.GetString("LContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contac tMe.
        /// </summary>
        public static string LContactMe {
            get {
                return ResourceManager.GetString("LContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creativly.
        /// </summary>
        public static string LCreativly {
            get {
                return ResourceManager.GetString("LCreativly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CV.
        /// </summary>
        public static string LDownloadCV {
            get {
                return ResourceManager.GetString("LDownloadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string LEducation {
            get {
                return ResourceManager.GetString("LEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LEmail {
            get {
                return ResourceManager.GetString("LEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string LExperience {
            get {
                return ResourceManager.GetString("LExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Post.
        /// </summary>
        public static string LFeaturedPost {
            get {
                return ResourceManager.GetString("LFeaturedPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front ender İron Skecth.
        /// </summary>
        public static string LFrontEnderIronSketch {
            get {
                return ResourceManager.GetString("LFrontEnderIronSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Stack Compar Academy.
        /// </summary>
        public static string LFullStackComparAcademy {
            get {
                return ResourceManager.GetString("LFullStackComparAcademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LHome {
            get {
                return ResourceManager.GetString("LHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since beginning my journey as a freelance designer nearly 8 years ago, I&apos;ve done remote work for agencies, consulted for startups, and collaborated with talented people to create digital products for both business and consumer use. I&apos;m quietly confident, naturally curious, and perpetually working on improving my chops one design problem at a time..
        /// </summary>
        public static string LNiceDescription {
            get {
                return ResourceManager.GetString("LNiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I’m Tural. Nice to meet you..
        /// </summary>
        public static string LNiceToMeet {
            get {
                return ResourceManager.GetString("LNiceToMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string LPhone {
            get {
                return ResourceManager.GetString("LPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan , Baku.
        /// </summary>
        public static string LPlace {
            get {
                return ResourceManager.GetString("LPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string LPortfolio {
            get {
                return ResourceManager.GetString("LPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using.
        /// </summary>
        public static string LPostDescrip {
            get {
                return ResourceManager.GetString("LPostDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management.
        /// </summary>
        public static string LProject {
            get {
                return ResourceManager.GetString("LProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Skills.
        /// </summary>
        public static string LProSkills {
            get {
                return ResourceManager.GetString("LProSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string LReadMore {
            get {
                return ResourceManager.GetString("LReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string LSkills {
            get {
                return ResourceManager.GetString("LSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum.
        /// </summary>
        public static string LStateDescrip {
            get {
                return ResourceManager.GetString("LStateDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Work.
        /// </summary>
        public static string LTeamWork {
            get {
                return ResourceManager.GetString("LTeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Skills.
        /// </summary>
        public static string LTSkills {
            get {
                return ResourceManager.GetString("LTSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tural Abdulkhaligov.
        /// </summary>
        public static string LTuralName {
            get {
                return ResourceManager.GetString("LTuralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I value simple content structure, clean design patterns, and thoughtful interactions. Things I enjoy designing: UX, UI, Web, Mobile, Apps, Logos.
        /// </summary>
        public static string LUİDescription {
            get {
                return ResourceManager.GetString("LUİDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Design.
        /// </summary>
        public static string LUIDesign {
            get {
                return ResourceManager.GetString("LUIDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like to code things from scratch, and enjoy bringing ideas to life in the browser. Languages I speak: HTML,C#, SQL, CSS, Sass, JS.
        /// </summary>
        public static string LWebDescrıptin {
            get {
                return ResourceManager.GetString("LWebDescrıptin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Developer.
        /// </summary>
        public static string LWebDeveloper {
            get {
                return ResourceManager.GetString("LWebDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Experience.
        /// </summary>
        public static string LWorkExperience {
            get {
                return ResourceManager.GetString("LWorkExperience", resourceCulture);
            }
        }
    }
}
