//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeDB : DbContext
    {
        public ResumeDB()
            : base("name=ResumeDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AboutMe> tbl_AboutMe { get; set; }
        public virtual DbSet<tbl_AboutMePhoto> tbl_AboutMePhoto { get; set; }
        public virtual DbSet<tbl_Client> tbl_Client { get; set; }
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }
        public virtual DbSet<tbl_CV> tbl_CV { get; set; }
        public virtual DbSet<tbl_CVPhoto> tbl_CVPhoto { get; set; }
        public virtual DbSet<tbl_Education> tbl_Education { get; set; }
        public virtual DbSet<tbl_Post> tbl_Post { get; set; }
        public virtual DbSet<tbl_Pricing> tbl_Pricing { get; set; }
        public virtual DbSet<tbl_SkillLeft> tbl_SkillLeft { get; set; }
        public virtual DbSet<tbl_SkillRight> tbl_SkillRight { get; set; }
        public virtual DbSet<tbl_WhatIDo> tbl_WhatIDo { get; set; }
        public virtual DbSet<tbl_Work> tbl_Work { get; set; }
    }
}
