//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CV
    {
        public int Id { get; set; }
        public string Icon { get; set; }
        public string Fullname { get; set; }
        public string Job { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string place { get; set; }
        public string Link { get; set; }
    }
}
