//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Post
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string Header { get; set; }
        public string Header2 { get; set; }
        public string Description { get; set; }
        public string Button { get; set; }
    }
}
